### CREATE A NEW USER
POST http://localhost:3000/auth/signUp
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "12345"
}

### SignIn

POST http://localhost:3000/auth/signIn
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "12345"
}

### Get the current signed In User

GET http://localhost:3000/auth/whoami


### Sign out

POST  http://localhost:3000/auth/signOut


### FIND A SPECIFIC USER BY ID
GET http://localhost:3000/auth/2

### FIND ALL USERS WITH A GIVEN EMAIL
GET http://localhost:3000/auth?email=m.hany@damen.com

### DELETE A USER WITH AN GIVEN ID
DELETE http://localhost:3000/auth/3

### UPDATE A USER
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email": "m.rff@damen.com",
    "password": "ddddd324234dzf"
}